[package]
org = "ballerinax"
name = "postgresql"
version = "1.11.0"
authors = ["Ballerina"]
keywords = ["database", "client", "network", "SQL", "RDBMS", "PostgreSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-postgresql"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "postgresql-native"
version = "1.11.0"
path = "../native/build/libs/postgresql-native-1.11.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "sql-native"
version = "1.11.0"
path = "./lib/sql-native-1.11.0-20230815-094200-9d12228.jar"

